routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', 'HomeController@index');

Route::resource('radAccts', 'RadAcctController');

app/Models/RadAcct.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class RadAcct
 * @package App\Models
 * @version May 2, 2018, 1:59 pm UTC
 *
 * @property string username
 * @property string acctstarttime
 * @property string acctstoptime
 * @property string calledstationid
 */
class RadAcct extends Model
{
    use SoftDeletes;

    public $table = 'radacct';


    protected $dates = ['deleted_at'];


    public $fillable = [
        'username',
        'acctstarttime',
        'acctstoptime',
        'calledstationid'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'username' => 'string',
        'acctstarttime' => 'string',
        'acctstoptime' => 'string',
        'calledstationid' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'username' => 'required'
    ];


}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/AppBaseController.php
<?php

namespace App\Http\Controllers;

use InfyOm\Generator\Utils\ResponseUtil;
use Response;

/**
 * @SWG\Swagger(
 *   basePath="/api/v1",
 *   @SWG\Info(
 *     title="Laravel Generator APIs",
 *     version="1.0.0",
 *   )
 * )
 * This class should be parent class for other API controllers
 * Class AppBaseController
 */
class AppBaseController extends Controller
{
    public function sendResponse($result, $message)
    {
        return Response::json(ResponseUtil::makeResponse($message, $result));
    }

    public function sendError($error, $code = 404)
    {
        return Response::json(ResponseUtil::makeError($error), $code);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/RadAcctController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateRadAcctRequest;
use App\Http\Requests\UpdateRadAcctRequest;
use App\Repositories\RadAcctRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class RadAcctController extends AppBaseController
{
    /** @var  RadAcctRepository */
    private $radAcctRepository;

    public function __construct(RadAcctRepository $radAcctRepo)
    {
        $this->radAcctRepository = $radAcctRepo;
    }

    /**
     * Display a listing of the RadAcct.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->radAcctRepository->pushCriteria(new RequestCriteria($request));
        $radAccts = $this->radAcctRepository->paginate(25);

        return view('rad_accts.index')
            ->with('radAccts', $radAccts);
    }

    /**
     * Show the form for creating a new RadAcct.
     *
     * @return Response
     */
    public function create()
    {
        return view('rad_accts.create');
    }

    /**
     * Store a newly created RadAcct in storage.
     *
     * @param CreateRadAcctRequest $request
     *
     * @return Response
     */
    public function store(CreateRadAcctRequest $request)
    {
        $input = $request->all();

        $radAcct = $this->radAcctRepository->create($input);

        Flash::success('Rad Acct saved successfully.');

        return redirect(route('radAccts.index'));
    }

    /**
     * Display the specified RadAcct.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $radAcct = $this->radAcctRepository->findWithoutFail($id);

        if (empty($radAcct)) {
            Flash::error('Rad Acct not found');

            return redirect(route('radAccts.index'));
        }

        return view('rad_accts.show')->with('radAcct', $radAcct);
    }

    /**
     * Show the form for editing the specified RadAcct.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $radAcct = $this->radAcctRepository->findWithoutFail($id);

        if (empty($radAcct)) {
            Flash::error('Rad Acct not found');

            return redirect(route('radAccts.index'));
        }

        return view('rad_accts.edit')->with('radAcct', $radAcct);
    }

    /**
     * Update the specified RadAcct in storage.
     *
     * @param  int              $id
     * @param UpdateRadAcctRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateRadAcctRequest $request)
    {
        $radAcct = $this->radAcctRepository->findWithoutFail($id);

        if (empty($radAcct)) {
            Flash::error('Rad Acct not found');

            return redirect(route('radAccts.index'));
        }

        $radAcct = $this->radAcctRepository->update($request->all(), $id);

        Flash::success('Rad Acct updated successfully.');

        return redirect(route('radAccts.index'));
    }

    /**
     * Remove the specified RadAcct from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $radAcct = $this->radAcctRepository->findWithoutFail($id);

        if (empty($radAcct)) {
            Flash::error('Rad Acct not found');

            return redirect(route('radAccts.index'));
        }

        $this->radAcctRepository->delete($id);

        Flash::success('Rad Acct deleted successfully.');

        return redirect(route('radAccts.index'));
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">


    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>InfyOm Generator</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">

    <!-- Theme style -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.4.2/css/AdminLTE.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.4.2/css/skins/_all-skins.min.css">

    <!-- iCheck -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/skins/square/_all.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css">

    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

    @yield('css')
</head>

<body class="skin-blue sidebar-mini">
@if (!Auth::guest())
    <div class="wrapper">
        <!-- Main Header -->
        <header class="main-header">

            <!-- Logo -->
            <a href="#" class="logo">
                <b>InfyOm</b>
            </a>

            <!-- Header Navbar -->
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <!-- Navbar Right Menu -->
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- User Account Menu -->
                        <li class="dropdown user user-menu">
                            <!-- Menu Toggle Button -->
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <!-- The user image in the navbar-->
                                <img src="http://infyom.com/images/logo/blue_logo_150x150.jpg"
                                     class="user-image" alt="User Image"/>
                                <!-- hidden-xs hides the username on small devices so only the image appears. -->
                                <span class="hidden-xs">{!! Auth::user()->name !!}</span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- The user image in the menu -->
                                <li class="user-header">
                                    <img src="http://infyom.com/images/logo/blue_logo_150x150.jpg"
                                         class="img-circle" alt="User Image"/>
                                    <p>
                                        {!! Auth::user()->name !!}
                                        <small>Member since {!! Auth::user()->created_at->format('M. Y') !!}</small>
                                    </p>
                                </li>
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a href="#" class="btn btn-default btn-flat">Profile</a>
                                    </div>
                                    <div class="pull-right">
                                        <a href="{!! url('/logout') !!}" class="btn btn-default btn-flat"
                                            onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                            Sign out
                                        </a>
                                        <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>

        <!-- Left side column. contains the logo and sidebar -->
        @include('layouts.sidebar')
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            @yield('content')
        </div>

        <!-- Main Footer -->
        <footer class="main-footer" style="max-height: 100px;text-align: center">
            <strong>Copyright © 2016 <a href="#">Company</a>.</strong> All rights reserved.
        </footer>

    </div>
@else
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{!! url('/') !!}">
                    InfyOm Generator
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    <li><a href="{!! url('/home') !!}">Home</a></li>
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    <li><a href="{!! url('/login') !!}">Login</a></li>
                    <li><a href="{!! url('/register') !!}">Register</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div id="page-content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    @yield('content')
                </div>
            </div>
        </div>
    </div>
    @endif

    <!-- jQuery 3.1.1 -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <!-- AdminLTE App -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.4.2/js/adminlte.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/icheck.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>

    @yield('scripts')
</body>
</html>

resources/views/layouts/datatables_css.blade.php
<!-- DataTable Bootstrap -->
<link href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="//cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.2.2/css/buttons.bootstrap.min.css">

resources/views/layouts/datatables_js.blade.php
<!-- Datatables -->
<script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.colVis.min.js"></script>
<script src="{{ asset('vendor/datatables/buttons.server-side.js') }}"></script>

resources/views/layouts/menu.blade.php
<li class="{{ Request::is('radAccts*') ? 'active' : '' }}">
    <a href="{!! route('radAccts.index') !!}"><i class="fa fa-edit"></i><span>Rad Accts</span></a>
</li>

resources/views/layouts/sidebar.blade.php
<aside class="main-sidebar" id="sidebar-wrapper">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        <!-- Sidebar user panel (optional) -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="http://infyom.com/images/logo/blue_logo_150x150.jpg" class="img-circle"
                     alt="User Image"/>
            </div>
            <div class="pull-left info">
                @if (Auth::guest())
                <p>InfyOm</p>
                @else
                    <p>{{ Auth::user()->name}}</p>
                @endif
                <!-- Status -->
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>

        <!-- search form (Optional) -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search..."/>
          <span class="input-group-btn">
            <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i>
            </button>
          </span>
            </div>
        </form>
        <!-- Sidebar Menu -->

        <ul class="sidebar-menu">
            @include('layouts.menu')
        </ul>
        <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>

resources/views/rad_accts/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Rad Acct
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'radAccts.store']) !!}

                        @include('rad_accts.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/rad_accts/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Rad Acct
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($radAcct, ['route' => ['radAccts.update', $radAcct->id], 'method' => 'patch']) !!}

                        @include('rad_accts.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/rad_accts/fields.blade.php
<!-- Username Field -->
<div class="form-group col-sm-6">
    {!! Form::label('username', 'Username:') !!}
    {!! Form::text('username', null, ['class' => 'form-control']) !!}
</div>

<!-- Acctstarttime Field -->
<div class="form-group col-sm-6">
    {!! Form::label('acctstarttime', 'Acctstarttime:') !!}
    {!! Form::text('acctstarttime', null, ['class' => 'form-control']) !!}
</div>

<!-- Acctstoptime Field -->
<div class="form-group col-sm-6">
    {!! Form::label('acctstoptime', 'Acctstoptime:') !!}
    {!! Form::text('acctstoptime', null, ['class' => 'form-control']) !!}
</div>

<!-- Calledstationid Field -->
<div class="form-group col-sm-6">
    {!! Form::label('calledstationid', 'Calledstationid:') !!}
    {!! Form::text('calledstationid', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('radAccts.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/rad_accts/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Rad Accts</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('radAccts.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('rad_accts.table')
            </div>
        </div>
        <div class="text-center">
        
        @include('adminlte-templates::common.paginate', ['records' => $radAccts])

        </div>
    </div>
@endsection

resources/views/rad_accts/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Rad Acct
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('rad_accts.show_fields')
                    <a href="{!! route('radAccts.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/rad_accts/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $radAcct->id !!}</p>
</div>

<!-- Username Field -->
<div class="form-group">
    {!! Form::label('username', 'Username:') !!}
    <p>{!! $radAcct->username !!}</p>
</div>

<!-- Acctstarttime Field -->
<div class="form-group">
    {!! Form::label('acctstarttime', 'Acctstarttime:') !!}
    <p>{!! $radAcct->acctstarttime !!}</p>
</div>

<!-- Acctstoptime Field -->
<div class="form-group">
    {!! Form::label('acctstoptime', 'Acctstoptime:') !!}
    <p>{!! $radAcct->acctstoptime !!}</p>
</div>

<!-- Calledstationid Field -->
<div class="form-group">
    {!! Form::label('calledstationid', 'Calledstationid:') !!}
    <p>{!! $radAcct->calledstationid !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $radAcct->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $radAcct->updated_at !!}</p>
</div>

resources/views/rad_accts/table.blade.php
<table class="table table-responsive" id="radAccts-table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Username</th>
            <th>Acctstarttime</th>
            <th>Acctstoptime</th>
            <th>Calledstationid</th>
            <th colspan="3">Action</th>
        </tr>
    </thead>
    <tbody>
    @foreach($radAccts as $radAcct)
        <tr>
            <td>{!! $radAcct->radacctid !!}</td>
            <td>{!! $radAcct->username !!}</td>
            <td>{!! $radAcct->acctstarttime !!}</td>
            <td>{!! $radAcct->acctstoptime !!}</td>
            <td>{!! $radAcct->calledstationid !!}</td>
            <td>
                {!! Form::open(['route' => ['radAccts.destroy', $radAcct->radacctid], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('radAccts.show', [$radAcct->radacctid]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('radAccts.edit', [$radAcct->radacctid]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>